---

- name: Load default interface configuration
  include_vars: "{{ item }}"
  with_first_found:
    - '../vars/{{ ifupdown_default_config }}.yml'
    - '../vars/networkmanager_{{ ifupdown_networkmanager }}.yml'
    - '../vars/virtualization_{{ ansible_virtualization_type }}_{{ ansible_virtualization_role }}.yml'
    - '../vars/default_{{ ifupdown_static_config }}.yml'
    - '../vars/default.yml'
  when: (ifupdown_interface is undefined or not ifupdown_interfaces)

- name: Prepare interface configuration if not defined
  set_fact:
    ifupdown_interfaces: '{{ ifupdown_default_interfaces }}'
  when: ((ifupdown_interfaces is undefined or not ifupdown_interfaces) and
         (ifupdown_dependent_interfaces is undefined and
         (ifupdown_default_interfaces is defined and ifupdown_default_interfaces)))

- name: Prepare interface configuration via dependency if defined
  set_fact:
    ifupdown_interfaces: '{{ ifupdown_dependent_interfaces }}'
  when: ifupdown_dependent_interfaces is defined and ifupdown_dependent_interfaces

- name: Create /etc/network/interfaces.d directory
  file:
    path: '/etc/network/interfaces.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Install bridge-utils if needed
  apt: name=bridge-utils state=present
  with_items: ifupdown_interfaces
  when: item.type is defined and item.type == 'bridge'

- name: Install ifenslave if needed
  apt: name=ifenslave state=present
  with_items: ifupdown_interfaces
  when: item.type is defined and item.type == 'bond'

- name: Delete interface configuration if requested
  file:
    path: '/etc/network/interfaces.d/{{ item.weight | default("00") }}_{{ item.filename | default(item.type | default("interface") + "_" + item.iface) }}'
    state: 'absent'
  with_items: ifupdown_interfaces
  when: ((item.iface is defined and item.iface) and
         (item.delete is defined and item.delete))

- name: Generate interface configuration
  template:
    src: 'etc/network/interfaces.d/{{ item.type | default("interface") }}.j2'
    dest: '/etc/network/interfaces.d/{{ item.weight | default("00") }}_{{ item.filename | default(item.type | default("interface") + "_" + item.iface) }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: ifupdown_interfaces
  register: ifupdown_register_status
  when: ((item.iface is defined and item.iface) and
         (item.delete is undefined or not item.delete))

- name: Reconfigure interfaces
  shell: ifdown {{ item.item.iface }} ; sleep {{ ifupdown_reconfigure_delay }} ; ifup {{ item.item.iface }}
  with_items: ifupdown_register_status.results
  when: ((ifupdown_register_status.results is defined and ifupdown_register_status.results) and
         (ifupdown_reconfigure is defined and ifupdown_reconfigure == True) and
         (item.changed == True) and
         (item.item.inet is undefined or item.item.inet != 'manual'))
